/* MESSAGE_MONITOR */

ALTER TABLE MESSAGE_MONITOR
ADD COLUMN TASK_NAME  VARCHAR(50) NOT NULL DEFAULT '-',
ADD COLUMN  MESSAGE_SUBJECT VARCHAR(50);

ALTER TABLE CUSTOMER_HISTORIES
MODIFY CUST_LOGIN VARCHAR(50);

ALTER TABLE AGENT_HISTORIES
MODIFY CUST_LOGIN VARCHAR(50);

ALTER TABLE CUST_REQ_FIRE
MODIFY ADDRESS VARCHAR(255);

ALTER TABLE `cust_req_emarine`
ADD COLUMN `NO_SURAT_JALAN` varchar(255) NULL

ALTER TABLE `cust_req_emarine`
	ADD COLUMN `NO_KUITANSI` varchar(25) NULL

